In [86]:
import pandas as pd
import numpy as np
import os

In [112]:
def drop_columns(df, cols):
    """
    This function removes the columns from a DataFrame.
    """
    for col in cols:
        try:
            df.drop([col], axis=1, inplace=True)
        except Exception as e:
            print(f"Bir hata oluştu: {e}")

In [113]:
files = os.listdir('hepsiemlak')
df = pd.concat([pd.read_csv(f"hepsiemlak/{file}") for file in files], ignore_index = True)


In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   img-link href        8136 non-null   object 
 1   photo-count          8130 non-null   float64
 2   list-view-price      8136 non-null   object 
 3   list-view-date       8136 non-null   object 
 4   celly                8136 non-null   object 
 5   celly 2              8136 non-null   object 
 6   celly 3              8136 non-null   object 
 7   celly 4              6858 non-null   object 
 8   list-view-header     8129 non-null   object 
 9   list-view-location   8136 non-null   object 
 10  he-lazy-image src    7649 non-null   object 
 11  left                 8114 non-null   object 
 12  img-wrp href         4555 non-null   object 
 13  he-lazy-image src 2  4067 non-null   object 
 14  branded__text        134 non-null    object 
 15  branded__text 2      134 non-null    o

In [115]:
df.head()

img-link href  photo-count  \
0  https://www.hepsiemlak.com/usak-banaz-cumhuriy...         10.0   
1  https://www.hepsiemlak.com/usak-merkez-kemaloz...         17.0   
2  https://www.hepsiemlak.com/usak-merkez-kemaloz...         11.0   
3  https://www.hepsiemlak.com/usak-merkez-durak-k...         13.0   
4  https://www.hepsiemlak.com/usak-merkez-cumhuri...         50.0   

  list-view-price list-view-date                           celly celly 2  \
0             7.0     15-04-2024  3 +\n                        1  150 m²   
1             8.5     07-04-2024  2 +\n                        1  110 m²   
2             7.0     29-03-2024  1 +\n                        1   60 m²   
3             7.0     30-03-2024  1 +\n                        1   50 m²   
4            16.5     30-03-2024  4 +\n                        1  300 m²   

                             celly 3 celly 4  \
0  20\n                      Yaşında   Kot 2   
1   8\n                      Yaşında  1. Kat   
2                         Sıfır Bina  4. Kat   
3  10\n                      Yaşında  5. Kat   
4  11\n                      Yaşında  7. Kat   

                                    list-view-header  \
0  Banazda Şehir Merkezinde Heryere Ulaşimi Çok Y...   
1         Kemalöz Semt Pazarı Yanı Kiralık 2+1 Daire   
2  Bakır Gayrimenkul Den Kiralık Atapark Yakını K...   
3      Fatih Caddesi Üzerinde Lüks Kiralık 1+1 Apart   
4  Uşak,Merkez,Cumhuriyet Mah.Kiralık 4+1 Dubleks...   

             list-view-location  \
0   Banaz, Cumhuriyet Mahallesi   
1     Merkez, Kemalöz Mahallesi   
2     Merkez, Kemalöz Mahallesi   
3       Merkez, Durak Mahallesi   
4  Merkez, Cumhuriyet Mahallesi   

                                   he-lazy-image src left img-wrp href  \
0                                                NaN  NaN          NaN   
1                                                NaN  NaN          NaN   
2                                                NaN  NaN          NaN   
3  https://hecdn01.hemlak.com/mncropresize/182/13...  NaN          NaN   
4  https://hecdn01.hemlak.com/mncropresize/182/13...  NaN          NaN   

  he-lazy-image src 2 branded__text branded__text 2 img-wrp href 2  \
0                 NaN           NaN             NaN            NaN   
1                 NaN           NaN             NaN            NaN   
2                 NaN           NaN             NaN            NaN   
3                 NaN           NaN             NaN            NaN   
4                 NaN           NaN             NaN            NaN   

  he-lazy-image src 3  
0                 NaN  
1                 NaN  
2                 NaN  
3                 NaN  
4                 NaN

In [116]:
df.columns

Index(['img-link href', 'photo-count', 'list-view-price', 'list-view-date',
       'celly', 'celly 2', 'celly 3', 'celly 4', 'list-view-header',
       'list-view-location', 'he-lazy-image src', 'left', 'img-wrp href',
       'he-lazy-image src 2', 'branded__text', 'branded__text 2',
       'img-wrp href 2', 'he-lazy-image src 3'],
      dtype='object')

In [117]:
cols = ['photo-count', 'list-view-date', 'list-view-header', 'list-view-location', 'he-lazy-image src', 'left', 'img-wrp href', 'he-lazy-image src 2', 'branded__text', 'branded__text 2', 'img-wrp href 2', 'he-lazy-image src 3']
drop_columns(df, cols)

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   img-link href    8136 non-null   object
 1   list-view-price  8136 non-null   object
 2   celly            8136 non-null   object
 3   celly 2          8136 non-null   object
 4   celly 3          8136 non-null   object
 5   celly 4          6858 non-null   object
dtypes: object(6)
memory usage: 381.5+ KB


In [119]:
df['location'] = df['img-link href'].apply(lambda x: x.split('/')[3])
df['city'] =  df['location'].str.split('-').str[0]
df['district'] =  df['location'].str.split('-').str[1]
df['neighborhood'] =  df['location'].str.split('-').str[2:-1]
df['neighborhood'] =  df['neighborhood'].apply(lambda x:'_'.join(x))


In [121]:
drop_columns(df, ['location', 'img-link href'])

Bir hata oluştu: "['location'] not found in axis"
Bir hata oluştu: "['img-link href'] not found in axis"


In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   list-view-price  8136 non-null   object
 1   celly            8136 non-null   object
 2   celly 2          8136 non-null   object
 3   celly 3          8136 non-null   object
 4   celly 4          6858 non-null   object
 5   city             8136 non-null   object
 6   district         8136 non-null   object
 7   neighborhood     8136 non-null   object
dtypes: object(8)
memory usage: 508.6+ KB


In [125]:
df[['city', 'district','neighborhood']].sample(20)

city      district              neighborhood
6823   manisa      turgutlu               selvilitepe
7440    mugla       dalaman                  karacali
2031    izmir       menemen                 kasimpasa
1920    izmir     karsiyaka                  bostanli
4922    izmir     karsiyaka               fikri_altay
2801    izmir       balcova                cetin_emec
7339    mugla        bodrum                 yalikavak
2462    izmir          urla               zeytinalani
7048    mugla      koycegiz                  beyobasi
5829    mugla       mentese                  orhaniye
3744    aydin      kusadasi                cumhuriyet
302     izmir         konak                kemal_reis
7518    mugla        bodrum                 yokusbasi
7356    mugla        ortaca                eksiliyurt
1661    izmir       bornova                kazimdirik
4499  denizli  merkezefendi               degirmenonu
5881    mugla       fethiye               menteseoglu
3614    aydin        efeler  hasanefendi_ramazan_pasa
7483    mugla         milas                    gulluk
4039  denizli     pamukkale               asmalievler

In [126]:
df.columns


Index(['list-view-price', 'celly', 'celly 2', 'celly 3', 'celly 4', 'city',
       'district', 'neighborhood'],
      dtype='object')

In [128]:
df['celly'].unique()

array(['3 +\n                        1', '2 +\n                        1',
       '1 +\n                        1', '4 +\n                        1',
       '2 +\n                        0', 'Stüdyo',
       '3 +\n                        0',
       '1 +\n                        15',
       '2 +\n                        2', '6 +\n                        2',
       '4 +\n                        2', '3 +\n                        2',
       '9 +\n                        1', '6 +\n                        1',
       '8 +\n                        1', '5 +\n                        1',
       '41 +\n                        4',
       '4 +\n                        0', '5 +\n                        2',
       '1 +\n                        25',
       '7 +\n                        1',
       '21 +\n                        1',
       '7 +\n                        2', '6 +\n                        0',
       '9 +\n                        4', '4 +\n                        4',
       '3 +\n           

In [132]:
df['celly'] = df['celly'].apply(lambda x: x.replace('Stüdyo', ' 1 + 0'))
df['celly'] = df['celly'].apply(lambda x: x.replace('\n', ''))
df['room'] = df['celly'].apply(lambda x: x.split('+')[0]).astype(int)
df['living_room'] = df['celly'].apply(lambda x: x.split('+')[1]).astype(int)

In [134]:
df['room'].unique()

array([ 3,  2,  1,  4,  6,  9,  8,  5, 41,  7, 21, 31, 25, 14, 10])

In [135]:
df['living_room'].unique()

array([ 1,  0, 15,  2,  4, 25,  3,  5,  9,  6])

In [136]:
drop_columns(df, ['celly'])

In [137]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   list-view-price  8136 non-null   object
 1   celly 2          8136 non-null   object
 2   celly 3          8136 non-null   object
 3   celly 4          6858 non-null   object
 4   city             8136 non-null   object
 5   district         8136 non-null   object
 6   neighborhood     8136 non-null   object
 7   room             8136 non-null   int64 
 8   living_room      8136 non-null   int64 
dtypes: int64(2), object(7)
memory usage: 572.2+ KB


In [140]:
df['celly 2'].unique()

array(['150 m²', '110 m²', '60 m²', '50 m²', '300 m²', '117 m²', '70 m²',
       '140 m²', '130 m²', '75 m²', '160 m²', '165 m²', '135 m²', '85 m²',
       '120 m²', '48 m²', '125 m²', '80 m²', '95 m²', '100 m²', '105 m²',
       '180 m²', '3.200 m²', '90 m²', '76 m²', '55 m²', '65 m²', '145 m²',
       '45 m²', '115 m²', '35 m²', '53 m²', '155 m²', '148 m²', '78 m²',
       '151 m²', '30 m²', '270 m²', '440 m²', '132 m²', '121 m²',
       '141 m²', '170 m²', '122 m²', '200 m²', '87 m²', '146 m²',
       '220 m²', '108 m²', '370 m²', '86 m²', '380 m²', '47 m²', '43 m²',
       '63 m²', '245 m²', '204 m²', '183 m²', '190 m²', '600 m²',
       '119 m²', '72 m²', '350 m²', '142 m²', '520 m²', '166 m²',
       '870 m²', '330 m²', '96 m²', '41 m²', '143 m²', '280 m²', '64 m²',
       '57 m²', '286 m²', '340 m²', '81 m²', '185 m²', '40 m²', '168 m²',
       '116 m²', '93 m²', '209 m²', '59 m²', '77 m²', '400 m²', '98 m²',
       '106 m²', '174 m²', '205 m²', '74 m²', '500 m²', '68 m²',
     

In [144]:
df['celly 2'] = df['celly 2'].apply(lambda x:x.replace('.',''))
df['area'] = df['celly 2'].apply(lambda x:x.split(' ')[0]).astype(int)


In [145]:
df['area'].unique()

array([ 150,  110,   60,   50,  300,  117,   70,  140,  130,   75,  160,
        165,  135,   85,  120,   48,  125,   80,   95,  100,  105,  180,
       3200,   90,   76,   55,   65,  145,   45,  115,   35,   53,  155,
        148,   78,  151,   30,  270,  440,  132,  121,  141,  170,  122,
        200,   87,  146,  220,  108,  370,   86,  380,   47,   43,   63,
        245,  204,  183,  190,  600,  119,   72,  350,  142,  520,  166,
        870,  330,   96,   41,  143,  280,   64,   57,  286,  340,   81,
        185,   40,  168,  116,   93,  209,   59,   77,  400,   98,  106,
        174,  205,   74,  500,   68, 1301,  275,   52,  137,  167,  217,
         25,  250,  290,  112,  196,  184,  450,  159,  195,  640,  230,
        260,  285,  235,  337,  211,  240,  134,  832, 1000,   38,  147,
        152,   88,  213,  126,  255,  199,  127,   11,  154,   22,   66,
        399,  187,   67,  210,   89,  355,   97,   84,   42,   51,   73,
        325,   71, 3000,  175,  320,  156,  162,   

In [147]:
drop_columns(df,['celly 2'])

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   list-view-price  8136 non-null   object
 1   celly 3          8136 non-null   object
 2   celly 4          6858 non-null   object
 3   city             8136 non-null   object
 4   district         8136 non-null   object
 5   neighborhood     8136 non-null   object
 6   room             8136 non-null   int64 
 7   living_room      8136 non-null   int64 
 8   area             8136 non-null   int64 
dtypes: int64(3), object(6)
memory usage: 572.2+ KB
