In [73]:
import pandas as pd
import numpy as np
import os

In [74]:
def drop_columns(df, cols):
    """
    This function removes the columns from a DataFrame.
    """
    for col in cols:
        try:
            df.drop([col], axis=1, inplace=True)
        except Exception as e:
            print(f"Bir hata oluştu: {e}")

In [75]:
files = os.listdir('hepsiemlak')
df = pd.concat([pd.read_csv(f"hepsiemlak/{file}") for file in files], ignore_index = True)


In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   img-link href        8136 non-null   object 
 1   photo-count          8130 non-null   float64
 2   list-view-price      8136 non-null   object 
 3   list-view-date       8136 non-null   object 
 4   celly                8136 non-null   object 
 5   celly 2              8136 non-null   object 
 6   celly 3              8136 non-null   object 
 7   celly 4              6858 non-null   object 
 8   list-view-header     8129 non-null   object 
 9   list-view-location   8136 non-null   object 
 10  he-lazy-image src    7649 non-null   object 
 11  left                 8114 non-null   object 
 12  img-wrp href         4555 non-null   object 
 13  he-lazy-image src 2  4067 non-null   object 
 14  branded__text        134 non-null    object 
 15  branded__text 2      134 non-null    o

In [77]:
df.head()

img-link href  photo-count  \
0  https://www.hepsiemlak.com/usak-banaz-cumhuriy...         10.0   
1  https://www.hepsiemlak.com/usak-merkez-kemaloz...         17.0   
2  https://www.hepsiemlak.com/usak-merkez-kemaloz...         11.0   
3  https://www.hepsiemlak.com/usak-merkez-durak-k...         13.0   
4  https://www.hepsiemlak.com/usak-merkez-cumhuri...         50.0   

  list-view-price list-view-date                           celly celly 2  \
0             7.0     15-04-2024  3 +\n                        1  150 m²   
1             8.5     07-04-2024  2 +\n                        1  110 m²   
2             7.0     29-03-2024  1 +\n                        1   60 m²   
3             7.0     30-03-2024  1 +\n                        1   50 m²   
4            16.5     30-03-2024  4 +\n                        1  300 m²   

                             celly 3 celly 4  \
0  20\n                      Yaşında   Kot 2   
1   8\n                      Yaşında  1. Kat   
2                         Sıfır Bina  4. Kat   
3  10\n                      Yaşında  5. Kat   
4  11\n                      Yaşında  7. Kat   

                                    list-view-header  \
0  Banazda Şehir Merkezinde Heryere Ulaşimi Çok Y...   
1         Kemalöz Semt Pazarı Yanı Kiralık 2+1 Daire   
2  Bakır Gayrimenkul Den Kiralık Atapark Yakını K...   
3      Fatih Caddesi Üzerinde Lüks Kiralık 1+1 Apart   
4  Uşak,Merkez,Cumhuriyet Mah.Kiralık 4+1 Dubleks...   

             list-view-location  \
0   Banaz, Cumhuriyet Mahallesi   
1     Merkez, Kemalöz Mahallesi   
2     Merkez, Kemalöz Mahallesi   
3       Merkez, Durak Mahallesi   
4  Merkez, Cumhuriyet Mahallesi   

                                   he-lazy-image src left img-wrp href  \
0                                                NaN  NaN          NaN   
1                                                NaN  NaN          NaN   
2                                                NaN  NaN          NaN   
3  https://hecdn01.hemlak.com/mncropresize/182/13...  NaN          NaN   
4  https://hecdn01.hemlak.com/mncropresize/182/13...  NaN          NaN   

  he-lazy-image src 2 branded__text branded__text 2 img-wrp href 2  \
0                 NaN           NaN             NaN            NaN   
1                 NaN           NaN             NaN            NaN   
2                 NaN           NaN             NaN            NaN   
3                 NaN           NaN             NaN            NaN   
4                 NaN           NaN             NaN            NaN   

  he-lazy-image src 3  
0                 NaN  
1                 NaN  
2                 NaN  
3                 NaN  
4                 NaN

In [78]:
df.columns

Index(['img-link href', 'photo-count', 'list-view-price', 'list-view-date',
       'celly', 'celly 2', 'celly 3', 'celly 4', 'list-view-header',
       'list-view-location', 'he-lazy-image src', 'left', 'img-wrp href',
       'he-lazy-image src 2', 'branded__text', 'branded__text 2',
       'img-wrp href 2', 'he-lazy-image src 3'],
      dtype='object')

In [79]:
cols = ['photo-count', 'list-view-date', 'list-view-header', 'list-view-location', 'he-lazy-image src', 'left', 'img-wrp href', 'he-lazy-image src 2', 'branded__text', 'branded__text 2', 'img-wrp href 2', 'he-lazy-image src 3']
drop_columns(df, cols)

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   img-link href    8136 non-null   object
 1   list-view-price  8136 non-null   object
 2   celly            8136 non-null   object
 3   celly 2          8136 non-null   object
 4   celly 3          8136 non-null   object
 5   celly 4          6858 non-null   object
dtypes: object(6)
memory usage: 381.5+ KB


In [81]:
df['location'] = df['img-link href'].apply(lambda x: x.split('/')[3])
df['city'] =  df['location'].str.split('-').str[0]
df['district'] =  df['location'].str.split('-').str[1]
df['neighborhood'] =  df['location'].str.split('-').str[2:-1]
df['neighborhood'] =  df['neighborhood'].apply(lambda x:'_'.join(x))


In [82]:
drop_columns(df, ['location', 'img-link href'])

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   list-view-price  8136 non-null   object
 1   celly            8136 non-null   object
 2   celly 2          8136 non-null   object
 3   celly 3          8136 non-null   object
 4   celly 4          6858 non-null   object
 5   city             8136 non-null   object
 6   district         8136 non-null   object
 7   neighborhood     8136 non-null   object
dtypes: object(8)
memory usage: 508.6+ KB


In [84]:
df[['city', 'district','neighborhood']].sample(20)

city      district           neighborhood
7726    mugla       fethiye                   foca
4673    izmir   seferihisar                tepecik
7591    mugla        bodrum                 gumbet
4081  denizli  merkezefendi               semikler
1203    izmir       bornova                 evka_3
7182    mugla        bodrum               mumcular
3716    aydin        efeler                   orta
833     izmir          buca              kurucesme
3005    aydin        efeler                 efeler
4896    izmir     karsiyaka               semikler
8021    mugla       mentese                kotekli
883     izmir     karsiyaka             cumhuriyet
2890    izmir          buca                  guven
3205    aydin        efeler             guzelhisar
451     izmir          foca  mustafa_kemal_ataturk
5920    mugla        bodrum                  geris
5557    mugla      marmaris              armutalan
7961    mugla      koycegiz               hamitkoy
6545    mugla        ortaca             cumhuriyet
8107    mugla       fethiye                ciftlik

In [85]:
df.columns


Index(['list-view-price', 'celly', 'celly 2', 'celly 3', 'celly 4', 'city',
       'district', 'neighborhood'],
      dtype='object')

In [86]:
df['celly'].unique()

array(['3 +\n                        1', '2 +\n                        1',
       '1 +\n                        1', '4 +\n                        1',
       '2 +\n                        0', 'Stüdyo',
       '3 +\n                        0',
       '1 +\n                        15',
       '2 +\n                        2', '6 +\n                        2',
       '4 +\n                        2', '3 +\n                        2',
       '9 +\n                        1', '6 +\n                        1',
       '8 +\n                        1', '5 +\n                        1',
       '41 +\n                        4',
       '4 +\n                        0', '5 +\n                        2',
       '1 +\n                        25',
       '7 +\n                        1',
       '21 +\n                        1',
       '7 +\n                        2', '6 +\n                        0',
       '9 +\n                        4', '4 +\n                        4',
       '3 +\n           

In [87]:
df['celly'] = df['celly'].apply(lambda x: x.replace('Stüdyo', ' 1 + 0'))
df['celly'] = df['celly'].apply(lambda x: x.replace('\n', ''))
df['room'] = df['celly'].apply(lambda x: x.split('+')[0]).astype(int)
df['living_room'] = df['celly'].apply(lambda x: x.split('+')[1]).astype(int)

In [88]:
df['room'].unique()

array([ 3,  2,  1,  4,  6,  9,  8,  5, 41,  7, 21, 31, 25, 14, 10])

In [89]:
df['living_room'].unique()

array([ 1,  0, 15,  2,  4, 25,  3,  5,  9,  6])

In [90]:
drop_columns(df, ['celly'])

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   list-view-price  8136 non-null   object
 1   celly 2          8136 non-null   object
 2   celly 3          8136 non-null   object
 3   celly 4          6858 non-null   object
 4   city             8136 non-null   object
 5   district         8136 non-null   object
 6   neighborhood     8136 non-null   object
 7   room             8136 non-null   int64 
 8   living_room      8136 non-null   int64 
dtypes: int64(2), object(7)
memory usage: 572.2+ KB


In [92]:
df['celly 2'].unique()

array(['150 m²', '110 m²', '60 m²', '50 m²', '300 m²', '117 m²', '70 m²',
       '140 m²', '130 m²', '75 m²', '160 m²', '165 m²', '135 m²', '85 m²',
       '120 m²', '48 m²', '125 m²', '80 m²', '95 m²', '100 m²', '105 m²',
       '180 m²', '3.200 m²', '90 m²', '76 m²', '55 m²', '65 m²', '145 m²',
       '45 m²', '115 m²', '35 m²', '53 m²', '155 m²', '148 m²', '78 m²',
       '151 m²', '30 m²', '270 m²', '440 m²', '132 m²', '121 m²',
       '141 m²', '170 m²', '122 m²', '200 m²', '87 m²', '146 m²',
       '220 m²', '108 m²', '370 m²', '86 m²', '380 m²', '47 m²', '43 m²',
       '63 m²', '245 m²', '204 m²', '183 m²', '190 m²', '600 m²',
       '119 m²', '72 m²', '350 m²', '142 m²', '520 m²', '166 m²',
       '870 m²', '330 m²', '96 m²', '41 m²', '143 m²', '280 m²', '64 m²',
       '57 m²', '286 m²', '340 m²', '81 m²', '185 m²', '40 m²', '168 m²',
       '116 m²', '93 m²', '209 m²', '59 m²', '77 m²', '400 m²', '98 m²',
       '106 m²', '174 m²', '205 m²', '74 m²', '500 m²', '68 m²',
     

In [93]:
df['celly 2'] = df['celly 2'].apply(lambda x:x.replace('.',''))
df['area'] = df['celly 2'].apply(lambda x:x.split(' ')[0]).astype(int)


In [94]:
df['area'].unique()

array([ 150,  110,   60,   50,  300,  117,   70,  140,  130,   75,  160,
        165,  135,   85,  120,   48,  125,   80,   95,  100,  105,  180,
       3200,   90,   76,   55,   65,  145,   45,  115,   35,   53,  155,
        148,   78,  151,   30,  270,  440,  132,  121,  141,  170,  122,
        200,   87,  146,  220,  108,  370,   86,  380,   47,   43,   63,
        245,  204,  183,  190,  600,  119,   72,  350,  142,  520,  166,
        870,  330,   96,   41,  143,  280,   64,   57,  286,  340,   81,
        185,   40,  168,  116,   93,  209,   59,   77,  400,   98,  106,
        174,  205,   74,  500,   68, 1301,  275,   52,  137,  167,  217,
         25,  250,  290,  112,  196,  184,  450,  159,  195,  640,  230,
        260,  285,  235,  337,  211,  240,  134,  832, 1000,   38,  147,
        152,   88,  213,  126,  255,  199,  127,   11,  154,   22,   66,
        399,  187,   67,  210,   89,  355,   97,   84,   42,   51,   73,
        325,   71, 3000,  175,  320,  156,  162,   

In [95]:
drop_columns(df,['celly 2'])

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   list-view-price  8136 non-null   object
 1   celly 3          8136 non-null   object
 2   celly 4          6858 non-null   object
 3   city             8136 non-null   object
 4   district         8136 non-null   object
 5   neighborhood     8136 non-null   object
 6   room             8136 non-null   int64 
 7   living_room      8136 non-null   int64 
 8   area             8136 non-null   int64 
dtypes: int64(3), object(6)
memory usage: 572.2+ KB


In [97]:
df['celly 3'].unique()

array(['20\n                      Yaşında',
       '8\n                      Yaşında', 'Sıfır Bina',
       '10\n                      Yaşında',
       '11\n                      Yaşında',
       '5\n                      Yaşında',
       '4\n                      Yaşında',
       '3\n                      Yaşında',
       '15\n                      Yaşında',
       '1\n                      Yaşında',
       '24\n                      Yaşında',
       '2\n                      Yaşında',
       '17\n                      Yaşında',
       '30\n                      Yaşında',
       '28\n                      Yaşında',
       '25\n                      Yaşında',
       '16\n                      Yaşında',
       '21\n                      Yaşında',
       '18\n                      Yaşında',
       '31\n                      Yaşında',
       '22\n                      Yaşında',
       '7\n                      Yaşında',
       '13\n                      Yaşında',
       '9\n              

In [98]:
df['celly 3'] = df['celly 3'].apply(lambda x:x.replace('Sıfır Bina', '0 yaşında'))
df['celly 3'] = df['celly 3'].apply(lambda x:x.replace('\n', ' '))
df['age'] = df['celly 3'].apply(lambda x:x.split(' ')[0]).astype(int)

In [99]:
df['age'].unique()

array([ 20,   8,   0,  10,  11,   5,   4,   3,  15,   1,  24,   2,  17,
        30,  28,  25,  16,  21,  18,  31,  22,   7,  13,   9,   6,  35,
        39,  14,  19,  33,  26,  12,  29,  49,  27,  32,  52,  40,  38,
        44,  50,  34,  23,  45,  42,  55,  36,  43,  37,  47, 300,  48,
       199, 100,  60,  61, 600])

In [100]:
drop_columns(df, ['celly 3'])

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   list-view-price  8136 non-null   object
 1   celly 4          6858 non-null   object
 2   city             8136 non-null   object
 3   district         8136 non-null   object
 4   neighborhood     8136 non-null   object
 5   room             8136 non-null   int64 
 6   living_room      8136 non-null   int64 
 7   area             8136 non-null   int64 
 8   age              8136 non-null   int64 
dtypes: int64(4), object(5)
memory usage: 572.2+ KB


In [102]:
df['celly 4'].unique()

array(['Kot 2', '1. Kat', '4. Kat', '5. Kat', '7. Kat', '3. Kat',
       '2. Kat', 'Kot 1', 'Yüksek Giriş', '9. Kat', 'Ara Kat',
       'En Üst Kat', 'Bahçe Katı', 'Yarı Bodrum', nan, 'Bodrum', 'Kot 3',
       'Çatı Katı', 'Zemin', '8. Kat', 'Giriş Katı', '6. Kat', '16. Kat',
       '17. Kat', 'Villa Katı', '10. Kat', '13. Kat', '12. Kat',
       '11. Kat', '14. Kat', '21 ve üzeri', 'Bodrum ve Zemin', 'Asma Kat',
       '18. Kat', 'Tripleks', 'Teras Katı', '15. Kat', '20. Kat',
       '19. Kat'], dtype=object)

In [104]:
replace_dict = {
    'Kot 2': '-2. Kat',
    'Kot 1': '-1. Kat',
    'Yüksek Giriş': '1. Kat',
    'Ara Kat': '3. Kat',
    'En Üst Kat': '5. Kat',
    'Bahçe Katı': '0. Kat',
    'Yarı Bodrum': '0. Kat',
    'Bodrum': '0. Kat',
    'Kot 3': '-3. Kat',
    'Çatı Katı': '5. Kat',
    'Zemin': '0. Kat',
    'Giriş Katı': '0. Kat',
    'Villa Katı': '0. Kat',
    '21 ve üzeri': '21. Kat',
    'Bodrum ve Zemin': '0. Kat',
    'Asma Kat': '1. Kat',
    'Tripleks': '0. Kat',
    'Teras Katı': '5. Kat',
    'nan': '2. Kat',
}
df['celly 4'] = df['celly 4'].replace(replace_dict.keys(), replace_dict.values()).astype(str)
df['celly 4'].dropna(inplace=True)
df['floor'] = df['celly 4'].apply(lambda x: x.split('.')[0]).astype(int)

In [105]:
df['floor'].unique()

array([-2,  1,  4,  5,  7,  3,  2, -1,  9,  0, -3,  8,  6, 16, 17, 10, 13,
       12, 11, 14, 21, 18, 15, 20, 19])

In [106]:
drop_columns(df, ['celly 4'])

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   list-view-price  8136 non-null   object
 1   city             8136 non-null   object
 2   district         8136 non-null   object
 3   neighborhood     8136 non-null   object
 4   room             8136 non-null   int64 
 5   living_room      8136 non-null   int64 
 6   area             8136 non-null   int64 
 7   age              8136 non-null   int64 
 8   floor            8136 non-null   int64 
dtypes: int64(5), object(4)
memory usage: 572.2+ KB


In [108]:
df['list-view-price'].unique()

array([7.0, 8.5, 16.5, 20.0, 22.0, 7.25, 15.0, 10.0, 7.5, 6.75, 21.0,
       14.0, 8.0, '7.500', '8.500', '15.000', '5.000', '7.000', '8.000',
       '11.000', '9.000', '3.000', '10.000', '6.500', '2.500', '6.000',
       '5.500', '8.750', '4.250', '4.500', '12.500', '5.250', '12.000',
       '7.250', '6.750', '7.750', '3.500', '6.600', '5.100', '13.000',
       '5.600', '1.100.000', '9.500', '4.000', '13.250', '19.000',
       '29.000', '30.000', '25.000', '18.500', '83.000', '14.000',
       '380.000', '20.000', '210.000', '280.000', '325.000', '16.000',
       '9.250', '37.500', '600.000', '350', '15.500', '500.000',
       '200.000', '20.500', '13.500', '11.500', '17.000', '800.000',
       '10.500', '22.000', '18.000', '50.000', '65.000', '550.000',
       '45.000', '33.000', '100.000', '21.500', '28.500', '26.000',
       '22.500', '220.000', '400.000', '39.000', '27.500', '16.500',
       '29.500', '15.750', '40.000', '21.750', '35.000', '25.500',
       '21.000', '235.000', '34

In [112]:
df['list-view-price'] = df['list-view-price'].astype(str).apply(lambda x:x.replace('.',''))
df['price'] = df['list-view-price'].astype(int)

In [113]:
df['price'].unique()

array([       70,        85,       165,       200,       220,       725,
             150,       100,        75,       675,       210,       140,
              80,      7500,      8500,     15000,      5000,      7000,
            8000,     11000,      9000,      3000,     10000,      6500,
            2500,      6000,      5500,      8750,      4250,      4500,
           12500,      5250,     12000,      7250,      6750,      7750,
            3500,      6600,      5100,     13000,      5600,   1100000,
            9500,      4000,     13250,     19000,     29000,     30000,
           25000,     18500,     83000,     14000,    380000,     20000,
          210000,    280000,    325000,     16000,      9250,     37500,
          600000,       350,     15500,    500000,    200000,     20500,
           13500,     11500,     17000,    800000,     10500,     22000,
           18000,     50000,     65000,    550000,     45000,     33000,
          100000,     21500,     28500,     26000, 

In [114]:
drop_columns(df, ['list-view-price'])

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   city          8136 non-null   object
 1   district      8136 non-null   object
 2   neighborhood  8136 non-null   object
 3   room          8136 non-null   int64 
 4   living_room   8136 non-null   int64 
 5   area          8136 non-null   int64 
 6   age           8136 non-null   int64 
 7   floor         8136 non-null   int64 
 8   price         8136 non-null   int64 
dtypes: int64(6), object(3)
memory usage: 572.2+ KB


In [116]:
df.to_csv('data.csv', index = False)